# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # aliased to a recent 5.4.x version
  - 5.4

install:
    - ./install.sh
# omitting "script:" will default to phpunit
script: phpunit --configuration phpunit.xml.dist --coverage-text tests/

# configure notifications (email, IRC, campfire etc)
notifications:
    email:
        - yourchev@gmail.com
